# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'ASHManager'
project 'ASHManager/ASHManager.xcodeproj'

def shared_pods
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
	
	# Pods for validator
	pod 'Validator'
	pod 'SwifterSwift' # –Over 500 in 1– for iOS, macOS, tvOS and watchOS
	# Pods for font
	pod 'FontAwesomeKit'
	# Pods for animation
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
	# Auto layout code
	pod 'SnapKit'
	
	# Pods for presentation
	# Color manager
	pod 'UIColor_Hex_Swift'
	# User defaults
	pod 'SwiftyUserDefaults'
	# Introduction
	pod 'EAIntroView'
	# Side Menu
	pod 'YALSideMenu'
	# Searching
	pod 'RAMReel'
	# Photo
	pod 'PreviewTransition'
	# Circular Slider
	pod 'HGCircularSlider'
	# Toast
	pod 'Toast-Swift'
	# Dialog
	pod 'PopupDialog'
	# Indicator
	pod 'NVActivityIndicatorView'
	# keyboard
	pod 'IQKeyboardManagerSwift'
	# Pull to refresh
	pod 'ESPullToRefresh', :git => 'https://github.com/eggswift/pull-to-refresh.git', :branch => 'master'
	# Fitness
	pod 'Charts'
	
	# Pod for sub items
	pod 'SelectableTextView'
	pod 'LTMorphingLabel'
	pod 'SkyFloatingLabelTextField'
	
	# Pods for Design pattern
	# Dependency injection
	pod 'Swinject'
	# Observer
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxGesture'
	
	# Pods for Network
	# Checking
	pod 'ReachabilitySwift'
	# HTTP
	pod 'Alamofire'
	# Abstration layer
	pod 'Moya'
	pod 'Moya/RxSwift'
	# Downloading and caching images
	pod 'Kingfisher'
	
	# Pods for Converter
	# Deal with json
	pod 'ObjectMapper'
	# Text to HTML format
	pod 'SwiftSoup'
	# Localization
	pod 'Localize-Swift'
	
	# Pods for ORM (Object relational mapping)
	pod 'RealmSwift'
	pod 'RxRealm'
	pod 'QueryKit'
	
	# Pods for Timing management
	pod 'DateToolsSwift' # For parsing
	pod 'Schedule' # For Plan
	pod 'JTAppleCalendar' # Calendar
	
	# Pods for Social network
	# Facebook
	pod 'Bolts'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	# Twitter
	pod 'TwitterKit'
	# Google
	pod 'GoogleSignIn'
	pod 'GooglePlaces'
	pod 'GoogleMaps'
	
	# Pods for In App Purchase
	pod 'SwiftyStoreKit'
	
	# Pods for Logger
	pod 'CocoaLumberjack/Swift'
end

target "ASEducation" do
	shared_pods
end

target "ASEducationDev" do
	shared_pods
end

#target 'ASHManagerTests' do
#	inherit! :search_paths
#	# Pods for testing
#	#	  pod 'Quick'
#	#	  pod 'Nimble'
#end
#
#target 'ASHManagerUITests' do
#	inherit! :search_paths
#	# Pods for testing
#	#	  pod 'Quick'
#	#	  pod 'Nimble'
#end
